🌏 convert cram to gvcf to public app
kids-first/kf-alignment-workflow pull request #103
Opened 2020-09-18 20:05 UTC by dmiller15

## Description

This PR creates a public app for the cram to gvcf workflow. It also updates the readme to include the link to the public app and pulls in the pipeline images directly from github so they populate the public app.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Pushed to apps-publisher and it pulls the files appropriately: https://cavatica.sbgenomics.com/u/cavatica/apps-publisher/apps/#cavatica/apps-publisher/kfdrc-gatk-haplotypecaller-workflow

**Test Configuration**:
* Environment: Cavatica
* Test files: None

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2020-09-18 21:17 UTC, migbro requested changes
Some minor change requests

2020-09-18 21:17 UTC, migbro commented on workflows/kfdrc-gatk-haplotypecaller-wf.cwl
> +  This workflow is the current production workflow, equivalent to this [Cavatica public app](https://cavatica.sbgenomics.com/public/apps#cavatica/apps-publisher/kfdrc-gatk-haplotypecaller-workflow)
Huh? There is one already? or is it the chicken and egg issue or readme vs doc?

2020-09-18 21:17 UTC, migbro commented on workflows/kfdrc-gatk-haplotypecaller-wf.cwl
> +
Please add in our fancy pants logo

2020-09-18 21:17 UTC, migbro commented on workflows/kfdrc-gatk-haplotypecaller-wf.cwl
> +  ## KFDRC GATK HaplotypeCaller CRAM to gVCF Workflow
Can drop this header as the `label` gets displayed anyway

2020-09-18 21:23 UTC, dmiller15 commented on workflows/kfdrc-gatk-haplotypecaller-wf.cwl
> +  This workflow is the current production workflow, equivalent to this [Cavatica public app](https://cavatica.sbgenomics.com/public/apps#cavatica/apps-publisher/kfdrc-gatk-haplotypecaller-workflow)
Chicken/egg shenanigans.

2020-09-18 21:25 UTC, dmiller15 commented on workflows/kfdrc-gatk-haplotypecaller-wf.cwl
> +
Added

2020-09-18 21:25 UTC, dmiller15 commented on workflows/kfdrc-gatk-haplotypecaller-wf.cwl
> +  ## KFDRC GATK HaplotypeCaller CRAM to gVCF Workflow
Done

2020-09-18 21:31 UTC, migbro requested changes

2020-09-18 21:31 UTC, migbro commented on workflows/kfdrc-gatk-haplotypecaller-wf.cwl
> +  This workflow is the current production workflow, equivalent to this [Cavatica public app](https://cavatica.sbgenomics.com/public/apps#cavatica/apps-publisher/kfdrc-gatk-haplotypecaller-workflow)
redundant, points back to app in this context

2020-09-18 21:33 UTC, migbro approved these changes

2020-10-01 20:14 UTC, sickler-alex approved these changes

2020-10-01 20:44 UTC, merged