Add fastqc
kids-first/kf-alignment-workflow pull request #106
Opened 2020-11-06 15:43 UTC by sickler-alex

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Adds a tool to run [FastQC](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/)

Fixes # 817 (partially)
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] [Cavatica test with bam input and returning FastQC raw data](https://cavatica.sbgenomics.com/u/d3b-bixu/dev-sample-qc/tasks/7fe859e9-4905-42e2-821f-e798c1e1cac7/)
- [ ] [Cavatica test with multiple fastq inputs](https://cavatica.sbgenomics.com/u/d3b-bixu/dev-sample-qc/tasks/f4e5b632-3ac7-45bb-a7d7-6265d7bc76a5/)

**Test Configuration**:
* Environment: Cavatica
* Test files:

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

2020-11-06 16:50 UTC, dmiller15 requested changes
I also can't see the test project. Add me please.

2020-11-06 16:50 UTC, dmiller15 commented on tools/fastqc.cwl
> +      - entryname: fastqc_params
do we have any rationale for these limits or expectations that they might change?

2020-11-06 16:50 UTC, dmiller15 commented on tools/fastqc.cwl
> +     -l fastqc_params -o .
I'm reading the tool help and there's an option for threads. You left it out of the options here, do you think there would be no benefit from its inclusion?

2020-11-06 16:50 UTC, dmiller15 commented on tools/fastqc.cwl
> +  sequences: {type: 'File[]', inputBinding: { position: 1 }, doc: "set of sequences being run can be either fastqs or bams"}
these should come last right? probably change the inputBinding position to 2 or 99 just to make sure it never gets put in front of the other position 1 arguments.

2020-11-06 16:50 UTC, dmiller15 commented on tools/fastqc.cwl
> +        }
I'm wondering if its better to have this be optional and return null in the else case. Returning an empty array might be less than ideal.

2020-11-09 15:17 UTC, sickler-alex commented on tools/fastqc.cwl
> +      - entryname: fastqc_params
Do you mainly mean the ram requirements? I took the initial requirements from the cellranger tool and added the InitialWorkDirRequirement requirement for the parameter file. The ram is set at 2 gigs, but should probably be finer tuned.

2020-11-09 18:46 UTC, dmiller15 commented on tools/fastqc.cwl
> +      - entryname: fastqc_params
No this question was about the fastqc params. Like why do we set warning and fail at certain levels? I was looking at the parameter file they had in the repo and it had comments about the different parameters.

2020-11-09 21:26 UTC, dmiller15 approved these changes

2020-11-09 21:37 UTC, migbro requested changes
Seems good overall, would like the comment I have made addressed real quick

2020-11-09 21:37 UTC, migbro commented on tools/fastqc.cwl
> +    ramMin: 2000
Piggy backing on Dan's comment, I think adding threads and ram defaults would be a good idea with the option to tweak - especially if we decide to try using the tool on a large cohort rather than many tasks. An example can be gleaned from this tool: https://github.com/kids-first/kf-somatic-workflow/blob/master/tools/vardictjava.cwl from the Reqs and inputs sections.

2020-11-11 18:30 UTC, migbro approved these changes
Pretty neat logic to use num files to inform cores, but have max cpu to take precedence so it doesn't get out of hand.

2020-11-12 21:07 UTC, dmiller15 approved these changes

2020-11-12 21:14 UTC, mark-welsh commented on tools/fastqc.cwl
> +      - entryname: fastqc_params
I have the same question. I would be wary about hardcoding these since for some experiments the thresholds could change

2020-11-13 18:31 UTC, merged