:zap: change fastqc tool to take parameter file as input
kids-first/kf-alignment-workflow pull request #107
Opened 2020-12-08 21:24 UTC by sickler-alex

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Update fastqc tool to take the parameter file as input.

Fixes # 866 (partially)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] [Cavatica test run](https://cavatica.sbgenomics.com/u/d3b-bixu/dev-sample-qc/tasks/283ae9d5-dd83-426b-97ca-4809456f340f/#)

**Test Configuration**:
* Environment: Cavatica
* Test files:

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

2020-12-10 20:16 UTC, dmiller15 approved these changes

2020-12-10 20:16 UTC, dmiller15 commented on tools/fastqc.cwl
> +  fastqc_params: {type: 'File', doc: "fastqc parameter file to use"}
This should be optional so users can just run with the default that exists in the repo: `/FastQC/Configuration/limits.txt`

2020-12-14 15:23 UTC, migbro requested changes
Just a minor request to fix and output name typo, I'll approve after that :)

2020-12-14 15:23 UTC, migbro commented on tools/fastqc.cwl
>    output_summarys:
Just a spelling thing: `output_summaries`

2020-12-15 14:39 UTC, migbro approved these changes
Looks good, thanks!

2020-12-16 16:28 UTC, merged