Add qc extras
kids-first/kf-alignment-workflow pull request #108
Opened 2020-12-17 18:30 UTC by sickler-alex

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Create a tool to calculate % Q20 and %Q30 from raw fastqc data.

Fixes # 866 (partially)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] https://cavatica.sbgenomics.com/u/d3b-bixu/dev-sample-qc/tasks/3090c92c-3743-4422-b0f0-01e6c0854436/#

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

2020-12-17 21:40 UTC, migbro requested changes
Small request to remove diagnostic print outs in script version, but looks good!

2020-12-17 21:40 UTC, migbro commented on scripts/calculate_extra_qc.py
> +    print(os.path.exists(file))
consider removing diagnostic stuff from file

2020-12-18 15:22 UTC, NHJohnson approved these changes
Looks great! I asked some questions but nothing major.

2020-12-18 15:22 UTC, NHJohnson commented on scripts/calculate_extra_qc.py
> +    total_base = 1.0
Does this start at 1 to avoid a ZeroDivisionError later on if there is no content in the file? If there are always a large number of basecalls I guess it doesn't matter, but you could use a try / except down there instead if there's the potential for the number to be small.

2020-12-18 15:22 UTC, NHJohnson commented on scripts/calculate_extra_qc.py
> +                process = 0
Could you `break` here to avoid processing the rest of the lines? Not sure how large these files are or if there's more than one quality section.

2020-12-18 15:22 UTC, NHJohnson commented on scripts/calculate_extra_qc.py
> +    print("sample_name,percent Q20, percent Q30")
Extra space after comma?

2020-12-18 15:53 UTC, migbro commented on scripts/calculate_extra_qc.py
> +                process = 0
Some good comments! Luckily this is a small file, but in general always a fan of avoiding extraneous processing

2021-01-04 19:43 UTC, NHJohnson approved these changes
Ok thanks! It seems pretty terrible that you have to painstakingly make the changes to both the .py file and the cwl. You would think there would be some way to just reference the former within the latter, but I guess there's not? New at this.

2021-01-04 19:46 UTC, sickler-alex commented
@NHJohnson I agree. I toyed around with the idea of making something to automatically insert a script / file into that section in the cwl tool, but decided not to since I wasn't super familiar with cwl yet. I might revisit that.

2021-01-08 22:21 UTC, migbro requested changes
I agree with Nathan's comment, please remove the extra space in the header that you print for the file: `print("sample_name,percent Q20, percent Q30")` right after `Q20,`. Then I think you're good to go!

2021-01-13 16:29 UTC, migbro approved these changes
Thanks for the change. Looks good!

2021-01-13 16:36 UTC, merged