🐎  sentieon wf
kids-first/kf-alignment-workflow pull request #120
Opened 2022-06-29 14:00 UTC by dmiller15

## Description

Creates a new alignment workflow using Sentieon's suite of tools. Small updates to existing tools. Still might need some cleanup. 

Closes https://github.com/d3b-center/bixu-tracker/issues/1404
Part of https://github.com/d3b-center/bixu-tracker/issues/1405

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

- [x] https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/75e3ebf6-ad5d-4871-9f80-066bfee384d7/
- [x] https://github.com/d3b-center/bixu-tracker/issues/1405

**Test Configuration**:
* Environment: cwltool and cavatica
* Test files: see cavatica test; also this ticket https://github.com/d3b-center/bixu-tracker/issues/1405

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have committed any related changes to the PR

2022-06-30 19:01 UTC, migbro requested changes
A couple comments on step naming I made. Also, Running cwltool complains of missing secondaryFiles for generate gvcf. Like, there is an oddity that two index files were created for the cram. Also, I think the BQSR step outputs `.bai` instead of `^.bai`

2022-06-30 19:30 UTC, luederm reviewed
I didn't get a chance to go through everything yet. I might come back to this later, but submitting now so you can see my comments so far

2022-06-30 19:30 UTC, luederm commented on tools/clt_flatten_filelist.cwl
> +            }
I'm confused about how this works. It looks like it is equivalent to `return inputs.input_files`.

2022-06-30 19:41 UTC, dmiller15 commented on tools/clt_flatten_filelist.cwl
> +  max_memory: { type: 'int?', default: 36, doc: "GB of RAM to allocate to the task." }
Correct. I want this task to always run on the same instance as the preceding task which is pretty heavy. A tool-level default value might not be the best way to do it in retrospect. I might lower the default here and set a value at the workflow level.

2022-06-30 19:41 UTC, dmiller15 commented on tools/clt_flatten_filelist.cwl
> +  cores: { type: 'int?', default: 36, doc: "Minimum reserved number of CPU cores for the task." }
I want this task to always run on the same instance as the preceding task which is pretty heavy. A tool-level default value might not be the best way to do it in retrospect. I might lower the default here and set a value at the workflow level.

2022-06-30 19:42 UTC, dmiller15 commented on tools/expression_flatten_filelist.cwl
> +  cores: { type: 'int?', default: 36, doc: "Minimum reserved number of CPU cores for the task." }
Yes I'll take it under consideration.

2022-06-30 19:54 UTC, dmiller15 commented on tools/clt_flatten_filelist.cwl
> +            }
input_files is a nested file array: `[[file1,file2,file3],[fileA,fileB,fileC]]`
We want to flatten that list so it is a flat file array.
```
> ret = []
[]
> input_files = [['file1','file2','file3'],['fileA','fileB','fileC']]
[ [ 'file1', 'file2', 'file3' ], [ 'fileA', 'fileB', 'fileC' ] ]
> ret = ret.concat(input_files[0])
[ 'file1', 'file2', 'file3' ]
> ret = ret.concat(input_files[1])
[ 'file1', 'file2', 'file3', 'fileA', 'fileB', 'fileC' ]
```
Long story short, I'm using concat to anneal a single-nested array into a flat array.

2022-06-30 20:00 UTC, dmiller15 commented on subworkflows/bwa_payload_to_realn_bam.cwl
> +id: rgbam_to_bwa_payload
Thanks! Good catch.

2022-06-30 20:00 UTC, dmiller15 commented on tools/clt_prepare_bwa_payload.cwl
> +id: expression_preparerg
Got it!

2022-06-30 20:26 UTC, dmiller15 commented
@migbro Yes there are the warnings about secondaryFile misalignment but ultimately those don't affect the running as you can see here: https://cavatica.sbgenomics.com/u/d3b-bixu/ha-bam-benchmarking/tasks/5c533287-cf85-4357-82f9-42e0a64bf523/. gVCF creation goes off without a hitch. Ultimately I think it's just that the gVCF workflow is a bit out of date and doesn't have the appropriate stuff. Since this PR explicitly avoids delving into the gVCF workflow I'd rather leave those warning resolutions for a different time.

2022-06-30 20:34 UTC, dmiller15 commented on tools/clt_flatten_filelist.cwl
> +  max_memory: { type: 'int?', default: 36, doc: "GB of RAM to allocate to the task." }
Ok I adjusted it so it's now being set at the workflow level. These values will be kept to the minimum since the tool doesn't have an inherent need for those resources.

2022-07-05 14:51 UTC, migbro approved these changes
Looks good, thanks! For the gVCF stuff, yeah, seems like a good idea to address in a separate PR. It may be that it is properly passing the files, or happens to be able to pull from the project instead of the un-bundled tar. I'd like to make sure it's not the latter as not every project will have all the files in the tar ball un-bundled already - that's kinda cheating.

2022-07-06 18:16 UTC, luederm approved these changes

2022-07-06 19:42 UTC, merged